CREATE TABLE Users(
userID INT PRIMARY KEY AUTO_INCREMENT,
firstName VARCHAR(30),
lastName VARCHAR(30),
gender VARCHAR(10),
emaildAdd VARCHAR(50) UNIQUE,
userPass TEXT,
userRole VARCHAR(6),
userProfile TEXT);

CREATE TABLE Products(
id INT PRIMARY KEY AUTO_INCREMENT,
prodName VARCHAR(25),
prodDescription VARCHAR(50),
category VARCHAR(25),
price DECIMAL(10, 2),
prodQuantity INT,
imgURL TEXT,
userID INT,
CONSTRAINT user_product FOREIGN KEY(userID)
REFERENCES Users(userID)
ON DELETE CASCADE
ON UPDATE CASCADE);
